spring.application.name=to-do-backend
spring.profiles.active=prod


# Enable all actuator endpoints
management.endpoints.web.exposure.include=*

# Or choose specific ones
# management.endpoints.web.exposure.include=health,info,metrics

# Change the base path if desired (default is /actuator)
management.endpoints.web.base-path=/actuator

# Show detailed health info
management.endpoint.health.show-details=always

#For custom path of the OpenAPI documentation in Json format, add a custom springdoc property, 
#in your spring-boot configuration file
springdoc.api-docs.path=/api-docs
#In order to display actuator endpoints, simply add this property:
springdoc.show-actuator=false
